// Imports
import 'package:world_time/services/worldTime.dart';
// locations
List<dynamic> locations = [
  IpTime(location: "Local Area", flag: "elementor-placeholder-image.png", url: "N/A", country: "Failed to load"),
  WorldTime(url: 'Africa/Abidjan', location: 'Abidjan', country: 'Ivory Coast', flag: 'ci.png'),
  WorldTime(url: 'Africa/Algiers', location: 'Algiers', country: 'Algeria', flag: 'dz.png'),
  WorldTime(url: 'Africa/Bissau', location: 'Bissau', country: 'Guinea-Bissau', flag: 'gw.png'),
  WorldTime(url: 'Africa/Cairo', location: 'Cairo', country: 'Egypt', flag: 'eg.png'),
  WorldTime(url: 'Africa/Casablanca', location: 'Casablanca', country: 'Morocco', flag: 'ma.png'),
  WorldTime(url: 'Africa/Ceuta', location: 'Ceuta', country: 'Spain', flag: 'es.png'),
  WorldTime(url: 'Africa/El_Aaiun', location: 'El Aaiun', country: 'Western Sahara', flag: 'eh.png'),
  WorldTime(url: 'Africa/Johannesburg', location: 'Johannesburg', country: 'South Africa', flag: 'za.png'),
  WorldTime(url: 'Africa/Juba', location: 'Juba', country: 'South Sudan', flag: 'ss.png'),
  WorldTime(url: 'Africa/Khartoum', location: 'Khartoum', country: 'Sudan', flag: 'sd.png'),
  WorldTime(url: 'Africa/Lagos', location: 'Lagos', country: 'Nigeria', flag: 'ng.png'),
  WorldTime(url: 'Africa/Maputo', location: 'Maputo', country: 'Mozambique', flag: 'mz.png'),
  WorldTime(url: 'Africa/Monrovia', location: 'Monrovia', country: 'Liberia', flag: 'lr.png'),
  WorldTime(url: 'Africa/Nairobi', location: 'Nairobi', country: 'Kenya', flag: 'ke.png'),
  WorldTime(url: 'Africa/Ndjamena', location: 'Ndjamena', country: 'Chad', flag: 'td.png'),
  WorldTime(url: 'Africa/Sao_Tome', location: 'Sao Tome', country: 'Sao Tome and Principe', flag: 'st.png'),
  WorldTime(url: 'Africa/Tripoli', location: 'Tripoli', country: 'Libya', flag: 'ly.png'),
  WorldTime(url: 'Africa/Tunis', location: 'Tunis', country: 'Tunisia', flag: 'tn.png'),
  WorldTime(url: 'Africa/Windhoek', location: 'Windhoek', country: 'Namibia', flag: 'na.png'),
  WorldTime(url: 'America/Adak', location: 'Adak', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Anchorage', location: 'Anchorage', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Araguaina', location: 'Araguaina', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Argentina/Buenos_Aires', location: 'Buenos Aires', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Catamarca', location: 'Catamarca', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Cordoba', location: 'Cordoba', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Jujuy', location: 'Jujuy', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/La_Rioja', location: 'La Rioja', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Mendoza', location: 'Mendoza', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Rio_Gallegos', location: 'Rio Gallegos', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Salta', location: 'Salta', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/San_Juan', location: 'San Juan', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/San_Luis', location: 'San Luis', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Tucuman', location: 'Tucuman', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Argentina/Ushuaia', location: 'Ushuaia', flag: 'ar.png', country: 'Argentina'),
  WorldTime(url: 'America/Asuncion', location: 'Asuncion', flag: 'py.png', country: 'Paraguay'),
  WorldTime(url: 'America/Bahia', location: 'Bahia', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Bahia_Banderas', location: 'Bahia Banderas', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Barbados', location: 'Barbados', flag: 'bb.png', country: 'Barbados'),
  WorldTime(url: 'America/Belem', location: 'Belem', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Belize', location: 'Belize', flag: 'bz.png', country: 'Belize'),
  WorldTime(url: 'America/Boa_Vista', location: 'Boa Vista', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Bogota', location: 'Bogota', flag: 'co.png', country: 'Colombia'),
  WorldTime(url: 'America/Boise', location: 'Boise', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Cambridge_Bay', location: 'Cambridge Bay', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Campo_Grande', location: 'Campo Grande', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Cancun', location: 'Cancun', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Caracas', location: 'Caracas', flag: 've.png', country: 'Venezuela'),
  WorldTime(url: 'America/Cayenne', location: 'Cayenne', flag: 'fr.png', country: 'French Guiana'),
  WorldTime(url: 'America/Chicago', location: 'Chicago', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Chihuahua', location: 'Chihuahua', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Ciudad_Juarez', location: 'Ciudad Juarez', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Costa_Rica', location: 'Costa Rica', flag: 'cr.png', country: 'Costa Rica'),
  WorldTime(url: 'America/Cuiaba', location: 'Cuiaba', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Danmarkshavn', location: 'Danmarkshavn', flag: 'gl.png', country: 'Greenland'),
  WorldTime(url: 'America/Dawson', location: 'Dawson', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Dawson_Creek', location: 'Dawson Creek', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Denver', location: 'Denver', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Detroit', location: 'Detroit', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Edmonton', location: 'Edmonton', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Eirunepe', location: 'Eirunepe', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/El_Salvador', location: 'El Salvador', flag: 'er.png', country: 'El Salvador'),
  WorldTime(url: 'America/Fort_Nelson', location: 'Fort Nelson', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Fortaleza', location: 'Fortaleza', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Glace_Bay', location: 'Glace Bay', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Goose_Bay', location: 'Goose Bay', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Grand_Turk', location: 'Grand Turk', flag: 'tc.png', country: 'Turks and Caicos Islands'),
  WorldTime(url: 'America/Guatemala', location: 'Guatemala', flag: 'gt.png', country: 'Guatemala'),
  WorldTime(url: 'America/Guayaquil', location: 'Guayaquil', flag: 'ec.png', country: 'Ecuador'),
  WorldTime(url: 'America/Guyana', location: 'Guyana', flag: 'gy.png', country: 'Guyana'),
  WorldTime(url: 'America/Halifax', location: 'Halifax', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Havana', location: 'Havana', flag: 'cu.png', country: 'Cuba'),
  WorldTime(url: 'America/Hermosillo', location: 'Hermosillo', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Indiana/Indianapolis', location: 'Indianapolis', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Knox', location: 'Knox', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Marengo', location: 'Marengo', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Petersburg', location: 'Petersburg', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Tell_City', location: 'Tell City', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Vevay', location: 'Vevay', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Vincennes', location: 'Vincennes', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Indiana/Winamac', location: 'Winamac', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Inuvik', location: 'Inuvik', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Iqaluit', location: 'Iqaluit', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Jamaica', location: 'Jamaica', flag: 'jm.png', country: 'Jamaica'),
  WorldTime(url: 'America/Juneau', location: 'Juneau', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Kentucky/Louisville', location: 'Louisville', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Kentucky/Monticello', location: 'Monticello', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/La_Paz', location: 'La Paz', flag: 'bo.png', country: 'Bolivia'),
  WorldTime(url: 'America/Lima', location: 'Lima', flag: 'pr.png', country: 'Peru'),
  WorldTime(url: 'America/Los_Angeles', location: 'Los Angeles', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Maceio', location: 'Maceio', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Managua', location: 'Managua', flag: 'ni.png', country: 'Nicaragua'),
  WorldTime(url: 'America/Manaus', location: 'Manaus', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Martinique', location: 'Martinique', flag: 'mq.png', country: 'Martinique'),
  WorldTime(url: 'America/Matamoros', location: 'Matamoros', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Mazatlan', location: 'Mazatlan', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Menominee', location: 'Menominee', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Merida', location: 'Merida', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Metlakatla', location: 'Metlakatla', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Mexico_City', location: 'Mexico City', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Miquelon', location: 'Miquelon', flag: 'pm.png', country: 'Saint Pierre and Miquelon'),
  WorldTime(url: 'America/Moncton', location: 'Moncton', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Monterrey', location: 'Monterrey', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Montevideo', location: 'Montevideo', flag: 'uy.png', country: 'Uruguay'),
  WorldTime(url: 'America/New_York', location: 'New York', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Nome', location: 'Nome', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Noronha', location: 'Fernando de Noronha', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/North_Dakota/Beulah', location: 'North Dakota - Beulah', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/North_Dakota/Center', location: 'North Dakota - Center', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/North_Dakota/New_Salem', location: 'North Dakota - New Salem', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Nuuk', location: 'Nuuk', flag: 'gl.png', country: 'Greenland'),
  WorldTime(url: 'America/Ojinaga', location: 'Ojinaga', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Panama', location: 'Panama', flag: 'pa.png', country: 'Panama'),
  WorldTime(url: 'America/Paramaribo', location: 'Paramaribo', flag: 'sr.png', country: 'Suriname'),
  WorldTime(url: 'America/Phoenix', location: 'Phoenix', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/Port-au-Prince', location: 'Port-au-Prince', flag: 'ht.png', country: 'Haiti'),
  WorldTime(url: 'America/Porto_Velho', location: 'Porto Velho', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Puerto_Rico', location: 'San Juan, Puerto Rico', flag: 'pr.png', country: 'Puerto Rico'),
  WorldTime(url: 'America/Punta_Arenas', location: 'Punta Arenas', flag: 'cl.png', country: 'Chile'),
  WorldTime(url: 'America/Rankin_Inlet', location: 'Rankin Inlet', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Recife', location: 'Recife', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Regina', location: 'Regina', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Resolute', location: 'Resolute', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Rio_Branco', location: 'Rio Branco', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Santarem', location: 'Santarem', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Santiago', location: 'Santiago', flag: 'cl.png', country: 'Chile'),
  WorldTime(url: 'America/Santo_Domingo', location: 'Santo Domingo', flag: 'do.png', country: 'Dominican Republic'),
  WorldTime(url: 'America/Sao_Paulo', location: 'Sao Paulo', flag: 'br.png', country: 'Brazil'),
  WorldTime(url: 'America/Scoresbysund', location: 'Scoresbysund', flag: 'gl.png', country: 'Greenland'),
  WorldTime(url: 'America/Sitka', location: 'Sitka', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'America/St_Johns', location: 'St. John\'s', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Swift_Current', location: 'Swift Current', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Tegucigalpa', location: 'Tegucigalpa', flag: 'hn.png', country: 'Honduras'),
  WorldTime(url: 'America/Thule', location: 'Thule', flag: 'gl.png', country: 'Greenland'),
  WorldTime(url: 'America/Tijuana', location: 'Tijuana', flag: 'mx.png', country: 'Mexico'),
  WorldTime(url: 'America/Toronto', location: 'Toronto', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Vancouver', location: 'Vancouver', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Whitehorse', location: 'Whitehorse', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Winnipeg', location: 'Winnipeg', flag: 'ca.png', country: 'Canada'),
  WorldTime(url: 'America/Yakutat', location: 'Yakutat', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'Antarctica/Casey', location: 'Casey', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Davis', location: 'Davis', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Macquarie', location: 'Macquarie Island', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Mawson', location: 'Mawson', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Palmer', location: 'Palmer', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Rothera', location: 'Rothera', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Antarctica/Troll', location: 'Troll', flag: 'aq.png', country: 'Antarctica'),
  WorldTime(url: 'Asia/Almaty', location: 'Almaty', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Amman', location: 'Amman', flag: 'jo.png', country: 'Jordan'),
  WorldTime(url: 'Asia/Anadyr', location: 'Anadyr', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Aqtau', location: 'Aqtau', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Aqtobe', location: 'Aqtobe', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Ashgabat', location: 'Ashgabat', flag: 'tm.png', country: 'Turkmenistan'),
  WorldTime(url: 'Asia/Atyrau', location: 'Atyrau', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Baghdad', location: 'Baghdad', flag: 'ir.png', country: 'Iraq'),
  WorldTime(url: 'Asia/Baku', location: 'Baku', flag: 'az.png', country: 'Azerbaijan'),
  WorldTime(url: 'Asia/Bangkok', location: 'Bangkok', flag: 'th.png', country: 'Thailand'),
  WorldTime(url: 'Asia/Barnaul', location: 'Barnaul', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Beirut', location: 'Beirut', flag: 'lb.png', country: 'Lebanon'),
  WorldTime(url: 'Asia/Bishkek', location: 'Bishkek', flag: 'kg.png', country: 'Kyrgyzstan'),
  WorldTime(url: 'Asia/Chita', location: 'Chita', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Choibalsan', location: 'Choibalsan', flag: 'mn.png', country: 'Mongolia'),
  WorldTime(url: 'Asia/Colombo', location: 'Colombo', flag: 'lk.png', country: 'Sri Lanka'),
  WorldTime(url: 'Asia/Damascus', location: 'Damascus', flag: 'sy.png', country: 'Syria'),
  WorldTime(url: 'Asia/Dhaka', location: 'Dhaka', flag: 'bd.png', country: 'Bangladesh'),
  WorldTime(url: 'Asia/Dili', location: 'Dili', flag: 'tl.png', country: 'Timor-Leste'),
  WorldTime(url: 'Asia/Dubai', location: 'Dubai', flag: 'ae.png', country: 'United Arab Emirates'),
  WorldTime(url: 'Asia/Dushanbe', location: 'Dushanbe', flag: 'tj.png', country: 'Tajikistan'),
  WorldTime(url: 'Asia/Famagusta', location: 'Famagusta', flag: 'cy.png', country: 'Cyprus'),
  WorldTime(url: 'Asia/Gaza', location: 'Gaza', flag: 'ps.png', country: 'Palestine'),
  WorldTime(url: 'Asia/Hebron', location: 'Hebron', flag: 'ps.png', country: 'Palestine'),
  WorldTime(url: 'Asia/Ho_Chi_Minh', location: 'Ho Chi Minh', flag: 'vn.png', country: 'Vietnam'),
  WorldTime(url: 'Asia/Hong_Kong', location: 'Hong Kong', flag: 'hk.png', country: 'Hong Kong'),
  WorldTime(url: 'Asia/Hovd', location: 'Hovd', flag: 'mn.png', country: 'Mongolia'),
  WorldTime(url: 'Asia/Irkutsk', location: 'Irkutsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Jakarta', location: 'Jakarta', flag: 'id.png', country: 'Indonesia'),
  WorldTime(url: 'Asia/Jayapura', location: 'Jayapura', flag: 'id.png', country: 'Indonesia'),
  WorldTime(url: 'Asia/Jerusalem', location: 'Jerusalem', flag: 'il.png', country: 'Israel'),
  WorldTime(url: 'Asia/Kabul', location: 'Kabul', flag: 'af.png', country: 'Afghanistan'),
  WorldTime(url: 'Asia/Kamchatka', location: 'Kamchatka', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Karachi', location: 'Karachi', flag: 'pk.png', country: 'Pakistan'),
  WorldTime(url: 'Asia/Kathmandu', location: 'Kathmandu', flag: 'np.png', country: 'Nepal'),
  WorldTime(url: 'Asia/Khandyga', location: 'Khandyga', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Kolkata', location: 'Kolkata', flag: 'in.png', country: 'India'),
  WorldTime(url: 'Asia/Krasnoyarsk', location: 'Krasnoyarsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Kuching', location: 'Kuching', flag: 'my.png', country: 'Malaysia'),
  WorldTime(url: 'Asia/Macau', location: 'Macau', flag: 'mo.png', country: 'Macau'),
  WorldTime(url: 'Asia/Magadan', location: 'Magadan', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Makassar', location: 'Makassar', flag: 'id.png', country: 'Indonesia'),
  WorldTime(url: 'Asia/Manila', location: 'Manila', flag: 'ph.png', country: 'Philippines'),
  WorldTime(url: 'Asia/Nicosia', location: 'Nicosia', flag: 'cy.png', country: 'Cyprus'),
  WorldTime(url: 'Asia/Novokuznetsk', location: 'Novokuznetsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Novosibirsk', location: 'Novosibirsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Omsk', location: 'Omsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Oral', location: 'Oral', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Pontianak', location: 'Pontianak', flag: 'id.png', country: 'Indonesia'),
  WorldTime(url: 'Asia/Pyongyang', location: 'Pyongyang', flag: 'kp.png', country: 'North Korea'),
  WorldTime(url: 'Asia/Qatar', location: 'Doha', flag: 'qa.png', country: 'Qatar'),
  WorldTime(url: 'Asia/Qostanay', location: 'Qostanay', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Qyzylorda', location: 'Qyzylorda', flag: 'kz.png', country: 'Kazakhstan'),
  WorldTime(url: 'Asia/Riyadh', location: 'Riyadh', flag: 'sa.png', country: 'Saudi Arabia'),
  WorldTime(url: 'Asia/Sakhalin', location: 'Sakhalin', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Samarkand', location: 'Samarkand', flag: 'uz.png', country: 'Uzbekistan'),
  WorldTime(url: 'Asia/Seoul', location: 'Seoul', flag: 'kr.png', country: 'South Korea'),
  WorldTime(url: 'Asia/Shanghai', location: 'Shanghai', flag: 'cn.png', country: 'china'),
  WorldTime(url: 'Asia/Singapore', location: 'Singapore', flag: 'sg.png', country: 'Singapore'),
  WorldTime(url: 'Asia/Srednekolymsk', location: 'Srednekolymsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Taipei', location: 'Taipei', flag: 'tw.png', country: 'Taiwan'),
  WorldTime(url: 'Asia/Tashkent', location: 'Tashkent', flag: 'uz.png', country: 'Uzbekistan'),
  WorldTime(url: 'Asia/Tbilisi', location: 'Tbilisi', flag: 'ge.png', country: 'Georgia'),
  WorldTime(url: 'Asia/Tehran', location: 'Tehran', flag: 'ir.png', country: 'Iran'),
  WorldTime(url: 'Asia/Thimphu', location: 'Thimphu', flag: 'bt.png', country: 'Bhutan'),
  WorldTime(url: 'Asia/Tokyo', location: 'Tokyo', flag: 'jp.png', country: 'Japan'),
  WorldTime(url: 'Asia/Tomsk', location: 'Tomsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Ulaanbaatar', location: 'Ulaanbaatar', flag: 'mn.png', country: 'Mongolia'),
  WorldTime(url: 'Asia/Urumqi', location: 'Urumqi', flag: 'cn.png', country: 'china'),
  WorldTime(url: 'Asia/Ust-Nera', location: 'Ust-Nera', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Vladivostok', location: 'Vladivostok', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Yakutsk', location: 'Yakutsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Yangon', location: 'Yangon', flag: 'mm.png', country: 'Myanmar'),
  WorldTime(url: 'Asia/Yekaterinburg', location: 'Yekaterinburg', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Asia/Yerevan', location: 'Yerevan', flag: 'am.png', country: 'Armenia'),
  WorldTime(url: 'Atlantic/Azores', location: 'Azores', flag: 'pt.png', country: 'Portugal'),
  WorldTime(url: 'Atlantic/Bermuda', location: 'Bermuda', flag: 'bm.png', country: 'Bermuda'),
  WorldTime(url: 'Atlantic/Canary', location: 'Canary Islands', flag: 'es.png', country: 'Spain'),
  WorldTime(url: 'Atlantic/Cape_Verde', location: 'Cape Verde', flag: 'cv.png', country: 'Cape Verde'),
  WorldTime(url: 'Atlantic/Faroe', location: 'Faroe', flag: 'dk.png', country: 'Denmark'),
  WorldTime(url: 'Atlantic/Madeira', location: 'Madeira', flag: 'pt.png', country: 'Portugal'),
  WorldTime(url: 'Atlantic/South_Georgia', location: 'South Georgia', flag: 'gb.png', country: 'United Kingdom'),
  WorldTime(url: 'Atlantic/Stanley', location: 'Stanley', flag: 'fk.png', country: 'Falkland Islands'),
  WorldTime(url: 'Australia/Adelaide', location: 'Adelaide', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Brisbane', location: 'Brisbane', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Broken_Hill', location: 'Broken Hill', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Darwin', location: 'Darwin', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Eucla', location: 'Eucla', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Hobart', location: 'Hobart', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Lindeman', location: 'Lindeman', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Lord_Howe', location: 'Lord Howe', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Melbourne', location: 'Melbourne', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Perth', location: 'Perth', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Australia/Sydney', location: 'Sydney', flag: 'au.png', country: 'Australia'),
  WorldTime(url: 'Europe/Andorra', location: 'Andorra', flag: 'ad.png', country: 'Andorra'),
  WorldTime(url: 'Europe/Astrakhan', location: 'Astrakhan', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Athens', location: 'Athens', flag: 'gr.png', country: 'Greece'),
  WorldTime(url: 'Europe/Belgrade', location: 'Belgrade', flag: 'rs.png', country: 'Serbia'),
  WorldTime(url: 'Europe/Berlin', location: 'Berlin', flag: 'de.png', country: 'Germany'),
  WorldTime(url: 'Europe/Brussels', location: 'Brussels', flag: 'be.png', country: 'Belgium'),
  WorldTime(url: 'Europe/Bucharest', location: 'Bucharest', flag: 'hu.png', country: 'Romania'),
  WorldTime(url: 'Europe/Budapest', location: 'Budapest', flag: 'hu.png', country: 'Hungary'),
  WorldTime(url: 'Europe/Chisinau', location: 'Chisinau', flag: 'md.png', country: 'Moldova'),
  WorldTime(url: 'Europe/Dublin', location: 'Dublin', flag: 'ie.png', country: 'Ireland'),
  WorldTime(url: 'Europe/Gibraltar', location: 'Gibraltar', flag: 'gb.png', country: 'United Kingdom'),
  WorldTime(url: 'Europe/Helsinki', location: 'Helsinki', flag: 'fi.png', country: 'Finland'),
  WorldTime(url: 'Europe/Istanbul', location: 'Istanbul', flag: 'tr.png', country: 'Turkey'),
  WorldTime(url: 'Europe/Kaliningrad', location: 'Kaliningrad', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Kirov', location: 'Kirov', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Kyiv', location: 'Kyiv', flag: 'ua.png', country: 'Ukraine'),
  WorldTime(url: 'Europe/Lisbon', location: 'Lisbon', flag: 'pt.png', country: 'Portugal'),
  WorldTime(url: 'Europe/London', location: 'London', flag: 'gb.png', country: 'United Kingdom'),
  WorldTime(url: 'Europe/Madrid', location: 'Madrid', flag: 'es.png', country: 'Spain'),
  WorldTime(url: 'Europe/Malta', location: 'Malta', flag: 'mt.png', country: 'Malta'),
  WorldTime(url: 'Europe/Minsk', location: 'Minsk', flag: 'by.png', country: 'Belarus'),
  WorldTime(url: 'Europe/Moscow', location: 'Moscow', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Paris', location: 'Paris', flag: 'fr.png', country: 'France'),
  WorldTime(url: 'Europe/Prague', location: 'Prague', flag: 'cz.png', country: 'Czech Republic'),
  WorldTime(url: 'Europe/Riga', location: 'Riga', flag: 'lt.png', country: 'Latvia'),
  WorldTime(url: 'Europe/Rome', location: 'Rome', flag: 'it.png', country: 'Italy'),
  WorldTime(url: 'Europe/Samara', location: 'Samara', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Saratov', location: 'Saratov', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Simferopol', location: 'Simferopol', flag: 'ua.png', country: 'Ukraine'),
  WorldTime(url: 'Europe/Sofia', location: 'Sofia', flag: 'bg.png', country: 'Bulgaria'),
  WorldTime(url: 'Europe/Tallinn', location: 'Tallinn', flag: 'ee.png', country: 'Estonia'),
  WorldTime(url: 'Europe/Tirane', location: 'Tirane', flag: 'al.png', country: 'Albania'),
  WorldTime(url: 'Europe/Ulyanovsk', location: 'Ulyanovsk', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Vienna', location: 'Vienna', flag: 'at.png', country: 'Austria'),
  WorldTime(url: 'Europe/Vilnius', location: 'Vilnius', flag: 'lt.png', country: 'Lithuania'),
  WorldTime(url: 'Europe/Volgograd', location: 'Volgograd', flag: 'ru.png', country: 'Russia'),
  WorldTime(url: 'Europe/Warsaw', location: 'Warsaw', flag: 'pl.png', country: 'Poland'),
  WorldTime(url: 'Europe/Zurich', location: 'Zurich', flag: 'ch.png', country: 'Switzerland'),
  WorldTime(url: 'Indian/Chagos', location: 'Chagos', flag: 'gb.png', country: 'United Kingdom'),
  WorldTime(url: 'Indian/Maldives', location: 'Maldives', flag: 'mv.png', country: 'Maldives'),
  WorldTime(url: 'Indian/Mauritius', location: 'Mauritius', flag: 'mu.png', country: 'Mauritius'),
  WorldTime(url: 'Pacific/Apia', location: 'Apia', flag: 'ws.png', country: 'Samoa'),
  WorldTime(url: 'Pacific/Auckland', location: 'Auckland', flag: 'nz.png', country: 'New Zealand'),
  WorldTime(url: 'Pacific/Bougainville', location: 'Bougainville', flag: 'pg.png', country: 'Papua New Guinea'),
  WorldTime(url: 'Pacific/Chatham', location: 'Chatham', flag: 'nz.png', country: 'New Zealand'),
  WorldTime(url: 'Pacific/Easter', location: 'Easter', flag: 'cl.png', country: 'Chile'),
  WorldTime(url: 'Pacific/Efate', location: 'Efate', flag: 'vu.png', country: 'Vanuatu'),
  WorldTime(url: 'Pacific/Fakaofo', location: 'Fakaofo', flag: 'tk.png', country: 'Tokelau'),
  WorldTime(url: 'Pacific/Fiji', location: 'Fiji', flag: 'fj.png', country: 'Fiji'),
  WorldTime(url: 'Pacific/Galapagos', location: 'Galapagos', flag: 'ec.png', country: 'Ecuador'),
  WorldTime(url: 'Pacific/Gambier', location: 'Gambier', flag: 'pf.png', country: 'French Polynesia'),
  WorldTime(url: 'Pacific/Guadalcanal', location: 'Guadalcanal', flag: 'Flag_of_the_Solomon_Islands.svg.png', country: 'Solomon Islands'),
  WorldTime(url: 'Pacific/Guam', location: 'Guam', flag: 'gu.png', country: 'Guam'),
  WorldTime(url: 'Pacific/Honolulu', location: 'Honolulu', flag: 'us.png', country: 'United States'),
  WorldTime(url: 'Pacific/Kanton', location: 'Kanton', flag: 'mh.png', country: 'Marshall Islands'),
  WorldTime(url: 'Pacific/Kiritimati', location: 'Kiritimati', flag: 'ki.png', country: 'Kiribati'),
  WorldTime(url: 'Pacific/Kosrae', location: 'Kosrae', flag: 'fm.png', country: 'Micronesia'),
  WorldTime(url: 'Pacific/Kwajalein', location: 'Kwajalein', flag: 'mh.png', country: 'Marshall Islands'),
  WorldTime(url: 'Pacific/Marquesas', location: 'Marquesas', flag: 'pf.png', country: 'French Polynesia'),
  WorldTime(url: 'Pacific/Nauru', location: 'Nauru', flag: 'nr.png', country: 'Nauru'),
  WorldTime(url: 'Pacific/Niue', location: 'Niue', flag: 'nu.png', country: 'Niue'),
  WorldTime(url: 'Pacific/Norfolk', location: 'Norfolk', flag: 'nf.png', country: 'Norfolk Island'),
  WorldTime(url: 'Pacific/Noumea', location: 'Noumea', flag: 'nc.png', country: 'New Caledonia'),
  WorldTime(url: 'Pacific/Pago_Pago', location: 'Pago Pago', flag: 'as.png', country: 'American Samoa'),
  WorldTime(url: 'Pacific/Palau', location: 'Palau', flag: 'pw.png', country: 'Palau'),
  WorldTime(url: 'Pacific/Pitcairn', location: 'Pitcairn', flag: 'pn.png', country: 'Pitcairn Islands'),
  WorldTime(url: 'Pacific/Port_Moresby', location: 'Port Moresby', flag: 'pg.png', country: 'Papua New Guinea'),
  WorldTime(url: 'Pacific/Rarotonga', location: 'Rarotonga', flag: 'ck.png', country: 'Cook Islands'),
  WorldTime(url: 'Pacific/Tahiti', location: 'Tahiti', flag: 'pf.png', country: 'French Polynesia'),
  WorldTime(url: 'Pacific/Tarawa', location: 'Tarawa', flag: 'ki.png', country: 'Kiribati'),
  WorldTime(url: 'Pacific/Tongatapu', location: 'Tongatapu', flag: 'to.png', country: 'Tonga'),
];